name: Setup EC2 with Ansible and Docker Image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag (e.g., commit SHA)'
        required: true
        default: 'latest'

jobs:
  setup-ec2:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Install Ansible & Pull Docker Image on EC2
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          # Install Ansible
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install -y ansible

          # Install Docker
          if ! command -v docker &> /dev/null
          then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
            sudo usermod -aG docker \$USER
          fi

          # Login to Docker Hub
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          # Pull Docker image
          docker pull ${{ secrets.DOCKER_USERNAME }}/some-image:${{ github.event.inputs.image_tag }}
EOF
